### ISSUE TITLE
URL Segment Params

### ISSUE THREAD

**Issue by hilkins** [numberly/flask2postman#2]
It could be nice to have a way to generate URL segment variables instead of global variables. It would be useful when you use common global variables between different collections but want some variables to be unique to some endpoints.

URL segment variables are defined using semi-colon `{{host}}/endpoint/:url_var/:another_url_var`.
I saw it referenced in that [issue](https://github.com/postmanlabs/postman-app-support/issues/85). :chicken:

**Comment by ramnes** [comment]
Yeah, we could make an option that force all the variables to be segment variables. But I think we should also find a way to differentiate which variable is supposed to be a global or a segment parameter. I'm not sure it's very useful to have only one type of variables.

**Comment by ramnes** [comment]
I don't think it's a useful feature, in comparison to the complexity it would add. I'll close this for now, but I (or someone else) will reopen it if there's a real need.
